import { Spatie } from "./spatie";

const nouns = ["ABYDOCOMIST",
    "BEDSWERVER",
    "BESPAWLER",
    "BOBOLYNE",
    "CUMBERWORLD",
    "DALCOP",
    "DEW-BEATER",
    "DORBEL",
    "DRATE-POKE",
    "DRIGGLE-DRAGGLE",
    "FOPDOODLE",
    "FUSTYLUGS",
    "FUSTILARIAN",
    "GILLIE-WET-FOOT",
    "GNASHGAB",
    "GOBERMOUCH",
    "GOWPENFUL-O'-ANYTHING",
    "KLAZOMANIAC",
    "LEASING-MONGER",
    "LOITER-SACK",
    "LUBBERWORT",
    "MUCK-SPOUT",
    "MUMBLECRUST",
    "QUISBY",
    "RAGGABRASH",
    "RAKEFIRE",
    "ROIDERBANKS",
    "SADDLE-GOOSE",
    "SCOBBERLOTCHER",
    "SKELPIE-LIMMER",
    "SMELL-FEAST",
    "SMELLFUNGUS",
    "SNOUTBAND",
    "SORNER",
    "STAMPCRAB",
    "STYMPHALIST",
    "TALLOWCATCH",
    "TRIPTAKER",
    "WANDOUGHT",
    "WHIFFLE-WHAFFLE",
    "YALDSON",
    "ZOILIST"];

const adjectives = [
    "Arrogant",
    "Big-headed",
    "Self-centred",
    "Vain",
    "Boastful",
    "Pompous",
    "Callous",
    "Cynical",
    "Overcritical",
    "Patronising",
    "Aloof",
    "Impolite",
    "Inconsiderate",
    "Thoughtless",
    "Confrontational",
    "Defensive",
    "Hostile",
    "Belligerent",
    "Bitchy",
    "Nasty",
    "Bossy",
    "Cruel",
    "Domineering",
    "Deceitful",
    "Dishonest",
    "Machiavellian",
    "Sneaky",
    "Untrustworthy",
    "Dogmatic",
    "Inflexible",
    "Intolerant",
    "Narrow-minded",
    "Stubborn",
    "Obstinate",
    "Pig-headed",
    "Fussy",
    "Indiscreet",
    "Tactless",
    "Unpredictable",
    "Vague",
    "Impatient",
    "Unreliable",
    "Jealous",
    "Possessive",
    "Resentful",
    "Secretive",
    "Idle",
    "Careless",
    "Irresponsible",
    "Untidy",
    "Cowardly",
    "Foolish",
    "Gullible",
    "Indecisive",
    "Weak-willed",
    "Quick-tempered",
    "Grumpy",
    "Moody",
    "Pessimistic",
    "Sullen",
    "Touchy",
    "Overemotional",
    "Clingy",
    "Finicky",
    "Silly",
    "Vulgar"
];

function getInsult(): string {
    var nounIndex = Spatie.getRandomNumber(0, nouns.length + 1);
    var adjIndex = Spatie.getRandomNumber(0, adjectives.length + 1);

    return adjectives[adjIndex] + " " + nouns[nounIndex];
}

export { getInsult };

